<?php

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use mootensai\behaviors\UUIDBehavior;

/**
 * This is the base model class for table "cuser".
 *
 * @property string $id
 * @property string $first_name
 * @property string $status_code
 * @property string $created_at
 * @property string $updated_at
 * @property string $status_description
 * @property double $commuter
 * @property string $hashed_password
 * @property double $enrolled
 * @property string $email
 * @property string $username
 */
class Cuser extends \yii\db\ActiveRecord
{

    use \mootensai\relation\RelationTrait;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['commuter', 'enrolled'], 'number'],
            [['id', 'first_name', 'status_description', 'username'], 'string', 'max' => 80],
            [['status_code'], 'string', 'max' => 20],
            [['created_at', 'updated_at'], 'string', 'max' => 6],
            [['hashed_password'], 'string', 'max' => 28],
            [['email'], 'string', 'max' => 125]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cuser';
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'first_name' => 'First Name',
            'status_code' => 'Status Code',
            'status_description' => 'Status Description',
            'commuter' => 'Commuter',
            'hashed_password' => 'Hashed Password',
            'enrolled' => 'Enrolled',
            'email' => 'Email',
            'username' => 'Username',
        );
    }

    public function beforeValidate()
    {
        if (empty($this->id)) {
            $this->id = uniqid() . uniqid();
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
